import os
import sys
import json

import argparse
import subprocess

from pathlib import Path
from pymongo import MongoClient, errors
from shapely.geometry import Polygon, Point, MultiPoint
from openslide import (OpenSlide, OpenSlideError,
                       OpenSlideUnsupportedFormatError)


def assure_path_exists(path):
    """
    If path exists, great.
    If not, then create it.
    :param path:
    :return:
    """
    m_dir = os.path.dirname(path)
    if not os.path.exists(m_dir):
        os.makedirs(m_dir)


def mongodb_connect(client_uri):
    """
    Connection routine
    :param client_uri:
    :return:
    """
    try:
        return MongoClient(client_uri, serverSelectionTimeoutMS=1)
    except errors.ConnectionFailure:
        print("Failed to connect to server {}".format(client_uri))
        exit(1)


def get_file_list(substr, filepath):
    """
    Find lines in data file containing substring.
    Return list.
    :param substr:
    :param filepath:
    :return:
    """
    lines = []
    with open(filepath) as f:
        for line in f:
            line = line.strip()
            if substr in line:
                lines.append(line)
    f.close()
    return lines


def copy_src_data(source_csv, source_svs, dest, m_caseid):
    """
    Copy data from nfs location to computation node.
    :param m_caseid:
    :param source_csv:
    :param source_svs:
    :param dest:
    :return:
    """
    # Get list of csv files containing features for this case_id
    csv_paths = get_file_list(m_caseid, 'config/csv_file_path.list')

    for csv_dir1 in csv_paths:
        source_dir = os.path.join(source_csv, csv_dir1)
        # copy all *.json and *features.csv files
        m_args = list(["rsync", "-ar", "--include", "*features.csv", "--include", "*.json"])
        # m_args = list(["rsync", "-avz", "--include", "*features.csv", "--include", "*.json"])
        m_args.append(source_dir)
        m_args.append(dest)
        print("executing " + ' '.join(m_args))
        subprocess.call(m_args)

    # Get slide
    my_file = Path(os.path.join(dest, (m_caseid + '.svs')))
    if not my_file.is_file():
        svs_list = get_file_list(m_caseid, 'config/image_path.list')
        svs_path = os.path.join(source_svs, svs_list[0])
        print("executing scp", svs_path, dest)
        subprocess.check_call(['scp', svs_path, dest])


def get_composite_exec_id(m_caseid):
    """
    There is only one composite dataset (unique execution_id) in quip_comp
    database for each image.
    :return:
    """
    m_dict = {}
    try:
        client = mongodb_connect('mongodb://' + args["db_host"] + ':27017')
        client.server_info()  # force connection, trigger error to be caught
        db = client.quip_comp
        coll = db.metadata
        query = {"image.case_id": m_caseid,
                 "provenance.analysis_execution_id": {'$regex': 'composite_dataset', '$options': 'i'}}
        m_dict = coll.find_one(query)
        client.close()
    except errors.ServerSelectionTimeoutError as err:
        print(err)
        exit(1)
    return m_dict['provenance']['analysis_execution_id']


def get_tumor_markup(m_caseid):
    """
    Find what the pathologist circled as tumor.
    :return:
    """
    tumor_markup_list = []
    execution_id = (user_name + "_Tumor_Region")
    try:
        client = mongodb_connect('mongodb://' + args["db_host"] + ':27017')
        client.server_info()  # force connection, trigger error to be caught
        db = client.quip
        coll = db.objects
        filter_q = {
            'provenance.image.case_id': m_caseid,
            'provenance.analysis.execution_id': execution_id
        }
        projection_q = {
            'geometry.coordinates': 1,
            '_id': 0
        }
        print(filter_q, projection_q)
        cursor = coll.find(filter_q, projection_q)
        for item in cursor:
            # geometry.coordinates happens to be a list with one thing in it: a list! (of point coordinates).
            points = item["geometry"]["coordinates"][0]  # dictionary to list
            tumor_markup_list.append(points)
        client.close()
    except errors.ServerSelectionTimeoutError as err:
        print(err)
        exit(1)

    count = len(tumor_markup_list)
    if count == 0:
        print("No tumor markups were generated by this user.")
        exit(0)

    print("count: ", count)
    return tumor_markup_list


def convert_to_polygons(markup_list):
    """
    Clean up and convert to something we can use.
    :param markup_list:
    :return:
    """
    m_poly_list = []
    try:
        # roll through our list of lists
        for coordinates in markup_list:
            m_polygon = point_to_poly(coordinates)
            # append to return-list
            poly_list.append(m_polygon)
    except Exception as ex:
        print(ex)
        exit(1)

    return m_poly_list


def point_to_poly(coordinates):
    """
    Create a polygon from [x,y]
    :param coordinates:
    :return:
    """
    points_list = []
    for m_point in coordinates:
        # convert the point coordinates to Points
        print(type(m_point), m_point)
        if type(m_point) == 'list':
            m_point1 = Point(m_point[0], m_point[1])
            points_list.append(m_point1)
    # create a Polygon
    m = MultiPoint(points_list)
    return Polygon(m)


def get_tile_metadata(local_img_folder, m_caseid):
    """
    Get tile w, h
    Get list of tile upper x, y from JSON files.
    :param local_img_folder:
    :param m_caseid:
    :return:
    """
    m_tlw = str(0)  # tile width
    m_tlh = str(0)  # tile height
    once = 0

    prefix_list = get_file_list(m_caseid, 'config/csv_file_path.list')
    tile_min_point_list = []
    for prefix in prefix_list:
        detail_local_folder = os.path.join(local_img_folder, prefix)
        if os.path.isdir(detail_local_folder) and len(os.listdir(detail_local_folder)) > 0:
            # Get list of JSON files we have to read
            json_filename_list = [f for f in os.listdir(detail_local_folder) if f.endswith('.json')]
            for json_filename in json_filename_list:
                # Read each JSON file
                with open(os.path.join(detail_local_folder, json_filename)) as f:
                    # f = _io.TextIOWrapper
                    data = json.load(f)

                    if once == 0:
                        once = 1
                        m_tlw = data["tile_width"]
                        m_tlh = data["tile_height"]

                    if m_tlw != data["tile_width"] or m_tlh != data["tile_height"]:
                        print("DIFF TILE W/H")
                        print(m_tlw, m_tlh)
                        exit(0)

                    m_tlw = data["tile_width"]
                    m_tlh = data["tile_height"]

                    # print('data', data)
                    # Get point
                    # point [67584, 45056]

                    tile_minx = data["tile_minx"]
                    tile_miny = data["tile_miny"]
                    point = [tile_minx, tile_miny]
                    tile_min_point_list.append(point)

    # tmp_set {(67584, 45056)} etc.
    tmp_set = set(map(tuple, tile_min_point_list))
    # for n in tmp_set:
    #     print(n)
    # convert to {[67584, 45056]}
    unique_tile_min_point_list = map(list, tmp_set)
    return m_tlw, m_tlh, unique_tile_min_point_list


def get_image_metadata(m_caseid):
    """
    Read slide and process
    :return:
    """
    p = Path(os.path.join(SLIDE_DIR, (m_caseid + '.svs')))
    osr = OpenSlide(str(p))
    # props = osr.properties
    # props.__getitem__('openslide.level[0].width')
    # props.__getitem__('openslide.level[0].height')
    image_width = osr.dimensions[0]
    image_height = osr.dimensions[1]
    osr.close()
    return image_width, image_height


# constant variables
WORK_DIR = "/data1/tdiprima/dataset"
CSV_FILE_PATH = "nfs004:/data/shared/bwang/composite_dataset"
SVS_IMAGE_PATH = "nfs001:/data/shared/tcga_analysis/seer_data/images"

# construct the argument parser and parse the arguments
ap = argparse.ArgumentParser()
ap.add_argument("-s", "--slide_name", help="svs image name")
ap.add_argument("-u", "--user_name", help="user who identified tumor regions")
ap.add_argument("-b", "--db_host", help="database host")
ap.add_argument("-t", "--tile_size", type=int, help="tile size")
args = vars(ap.parse_args())
print(args)

if not len(sys.argv) > 1:
    program_name = sys.argv[0]
    lst = ['python', program_name, '-h']
    subprocess.call(lst)  # Show help
    exit(1)

case_id = args["slide_name"]
user_name = args["user_name"]
SLIDE_DIR = os.path.join(WORK_DIR, case_id) + os.sep

# Fetch data
# assure_path_exists(SLIDE_DIR)
# copy_src_data(csv_file_path, svs_image_path, SLIDE_DIR, case_id)

# Find what the pathologist circled as tumor
tumor_mark_list = get_tumor_markup(case_id)
tumor_poly_list = convert_to_polygons(tumor_mark_list)

# Get exec_id for polygons
# composite_exec_id = get_composite_exec_id()

# IMAGE_WIDTH, IMAGE_HEIGHT = get_image_metadata(case_id)
# print(IMAGE_WIDTH, IMAGE_HEIGHT)

tile_width, tile_height, tile_coords_list = get_tile_metadata(WORK_DIR, case_id)
poly_list = []
for point in tile_coords_list:
    p = point_to_poly(point)
    poly_list.append(p)

# Testing for now.
within = 0
intersects = 0
disjoin = 0
for tumor_roi in tumor_poly_list:
    for polygon in poly_list:
        if polygon.within(tumor_roi):
            within += 1
        if polygon.intersects(tumor_roi):
            intersects += 1
        if polygon.disjoint(tumor_roi):
            disjoin += 1

print('within', within)
print('intersects', intersects)
print('disjoin', disjoin)
