import argparse
import json
import os
import subprocess
import sys
import time
from pathlib import Path

import pandas
from pymongo import MongoClient, errors
from shapely.geometry import Polygon, Point, MultiPoint


def assure_path_exists(path):
    """
    If path exists, great.
    If not, then create it.
    :param path:
    :return:
    """
    m_dir = os.path.dirname(path)
    if not os.path.exists(m_dir):
        os.makedirs(m_dir)


def mongodb_connect(client_uri):
    """
    Connection routine
    :param client_uri:
    :return:
    """
    try:
        return MongoClient(client_uri, serverSelectionTimeoutMS=1)
    except errors.ConnectionFailure:
        print("Failed to connect to server {}".format(client_uri))
        exit(1)


def get_file_list(substr, filepath):
    """
    Find lines in data file containing (case_id) substring.
    Return list.
    :param substr:
    :param filepath:
    :return:
    """
    lines = []
    with open(filepath) as f:
        for line in f:
            line = line.strip()
            if substr in line:
                lines.append(line)
    f.close()
    return lines


def copy_src_data(dest):
    """
    Copy data from nfs location to computation node.
    :param dest:
    :return:
    """
    # Get list of csv files containing features for this case_id
    for csv_dir1 in CSV_REL_PATHS:
        source_dir = os.path.join(CSV_FILE_PATH, csv_dir1)
        # copy all *.json and *features.csv files
        m_args = list(["rsync", "-ar", "--include", "*features.csv", "--include", "*.json"])
        # m_args = list(["rsync", "-avz", "--include", "*features.csv", "--include", "*.json"])
        m_args.append(source_dir)
        m_args.append(dest)
        print("executing " + ' '.join(m_args))
        subprocess.call(m_args)

    # Get slide
    my_file = Path(os.path.join(dest, (CASE_ID + '.svs')))
    if not my_file.is_file():
        svs_list = get_file_list(CASE_ID, 'config/image_path.list')
        svs_path = os.path.join(SVS_IMAGE_PATH, svs_list[0])
        print("executing scp", svs_path, dest)
        subprocess.check_call(['scp', svs_path, dest])


def get_tumor_markup(user_name):
    """
    Find what the pathologist circled as tumor.
    :param user_name:
    :return:
    """
    tumor_markup_list = []
    execution_id = (user_name + "_Tumor_Region")
    try:
        client = mongodb_connect('mongodb://' + args["db_host"] + ':27017')
        client.server_info()  # force connection, trigger error to be caught
        db = client.quip
        coll = db.objects
        filter_q = {
            'provenance.image.case_id': CASE_ID,
            'provenance.analysis.execution_id': execution_id
        }
        projection_q = {
            'geometry.coordinates': 1,
            '_id': 0
        }
        print('quip.objects')
        print(filter_q, ',', projection_q)
        cursor = coll.find(filter_q, projection_q)
        for item in cursor:
            # geometry.coordinates happens to be a list with one thing in it: a list! (of point coordinates).
            temp = item['geometry']['coordinates']  # [ [ [ x, y ], ... ] ]
            points = temp[0]  # [ [x, y ], ... ]
            tumor_markup_list.append(points)
        client.close()
    except errors.ServerSelectionTimeoutError as err:
        print('Error in get_tumor_markup', err)
        exit(1)

    count = len(tumor_markup_list)
    if count == 0:
        print('No tumor markups were generated by ', user_name)
        exit(1)

    print('Tumor markup count: ', count)
    return tumor_markup_list


def markup_to_polygons(markup_list):
    """
    Clean up and convert to something we can use.
    :param markup_list:
    :return:
    """
    m_poly_list = []
    try:
        # roll through our list of lists
        for coordinates in markup_list:
            points_list = []
            # convert the point coordinates to Points
            for m_point in coordinates:
                m_point = Point(m_point[0], m_point[1])
                points_list.append(m_point)
            # create a Polygon
            m = MultiPoint(points_list)
            m_polygon = Polygon(m)
            # append to return-list
            m_poly_list.append(m_polygon)
    except Exception as ex:
        print('Error in convert_to_polygons', ex)
        exit(1)

    # Return list of polygons
    return m_poly_list


def coordinates_to_polygons(coordinates_list):
    """
    Clean up and convert to something we can use.
    :param coordinates_list:
    :return:
    """
    m_poly_list = []
    points_list = []
    try:
        # roll through our list of [x,y]
        for m_point in coordinates_list:
            # convert the point coordinates to Points
            m_point = Point(m_point[0], m_point[1])
            points_list.append(m_point)
        # create a Polygon
        m = MultiPoint(points_list)
        m_polygon = Polygon(m)
        # append to return-list
        m_poly_list.append(m_polygon)
    except Exception as ex:
        print('Error in convert_to_polygons', ex)
        exit(1)

    # Return list of polygons
    return m_poly_list


def string_to_polygon(poly_data, imw, imh):
    """
    Convert Polygon string to polygon
    :param poly_data:
    :return:
    """
    points_list = []

    tmp_str = str(poly_data)
    tmp_str = tmp_str.replace('[', '')
    tmp_str = tmp_str.replace(']', '')
    split_str = tmp_str.split(':')
    m_polygon = {}

    try:
        # Get list of points
        for i in range(0, len(split_str) - 1, 2):
            a = float(split_str[i])
            b = float(split_str[i + 1])
            # Normalize points
            point = [a / float(imw), b / float(imh)]
            m_point = Point(point)
            points_list.append(m_point)
        # Create a Polygon
        m = MultiPoint(points_list)
        m_polygon = Polygon(m)
    except Exception as ex:
        print('Error in string_to_polygon', ex)
        exit(1)

    return m_polygon


def get_data_files():
    """
    Return 2 lists containing full paths for CSVs and JSONs.
    :return:
    """
    filenames = os.listdir(SLIDE_DIR)  # get all files' and folders' names in directory

    folders = []
    for filename in filenames:  # loop through all the files and folders
        ppath = os.path.join(os.path.abspath(SLIDE_DIR), filename)
        if os.path.isdir(ppath):  # check whether the current object is a folder or not
            folders.append(ppath)

    folders.sort()
    print('subfolders: ', len(folders))

    json_files = []
    csv_files = []
    for index, filename in enumerate(folders):
        # print(index, filename)
        files = os.listdir(filename)
        for name in files:
            ppath = os.path.join(os.path.abspath(filename), name)
            if name.endswith('json'):
                json_files.append(ppath)
            elif name.endswith('csv'):
                csv_files.append(ppath)

    print('json_files: ', len(json_files))
    print('csv_files: ', len(csv_files))

    json_files.sort()
    csv_files.sort()
    return json_files, csv_files


def create_map(json_files, csv_files):
    """
    Map out_file_prefix to polygons, so we can find out which polygons are within or intersect a tumor region,
    and then be able to re-access the corresponding json and csv data.
    :param json_files:
    :param csv_files:
    :return:
    """
    rtn_dict = {}
    start_time = time.time()

    for n, jfile in enumerate(json_files):
        with open(jfile, 'r') as f:
            # Read JSON data into the json_dict variable
            json_dict = json.load(f)
            str = json_dict['out_file_prefix']
            imw = json_dict['image_width']
            imh = json_dict['image_height']
            cfile = csv_files[n]

            if str not in cfile:
                print('There should be 1 json file for 1 csv file.')
                exit(1)

            # Read CSV data into the dataframe variable
            df = pandas.read_csv(cfile)
            if df.empty:
                continue
            else:
                # out_file_prefix = Series
                # path_poly[str] = df['Polygon']
                path_poly = {}
                newList = []
                series_to_list = df['Polygon'].tolist()
                for s in series_to_list:
                    poly = string_to_polygon(s, imw, imh)
                    newList.append(poly)
                polyinfo = {"polygons": newList, "image_width": imw, "image_height": imh}
                path_poly[str] = polyinfo

            rtn_dict.update(path_poly)

        f.close()
        # rtn_dict.update(path_poly)

    elapsed_time = time.time() - start_time
    print('Runtime create_map: ')
    print(time.strftime("%H:%M:%S", time.gmtime(elapsed_time)))

    return rtn_dict


def get_poly_within(jfiles, tumor_list):
    """
    Narrow it down...
    :param jfiles:
    :param tumor_list:
    :return:
    """
    print('files len: ', len(jfiles))
    print('tumor_list len: ', len(tumor_list))
    temp = {}
    path_poly = {}
    rtn_jfiles = []
    start_time = time.time()

    for jfile in jfiles:
        with open(jfile, 'r') as f:
            # Read JSON data into the json_dict variable
            json_dict = json.load(f)
            str = json_dict['out_file_prefix']
            imw = json_dict['image_width']
            imh = json_dict['image_height']
            tile_height = json_dict['tile_height']
            tile_width = json_dict['tile_width']
            tile_minx = json_dict['tile_minx']
            tile_miny = json_dict['tile_miny']
            inc_x = tile_minx + tile_width
            inc_y = tile_miny + tile_height
            point1 = Point(float(tile_minx) / float(imw), float(tile_miny) / float(imh))
            point2 = Point(float(inc_x) / float(imw), float(tile_miny) / float(imh))
            point3 = Point(float(inc_x) / float(imw), float(inc_y) / float(imh))
            point4 = Point(float(tile_minx) / float(imw), float(inc_y) / float(imh))
            point5 = Point(float(tile_minx) / float(imw), float(tile_miny) / float(imh))
            m = MultiPoint([point1, point2, point3, point4, point5])
            polygon = Polygon(m)
            path_poly[str] = polygon
        f.close()
        temp.update(path_poly)

    count = 0
    for tumor_roi in tumor_list:
        for key, val in temp.items():
            gotone = False
            # print("Key", key, 'points to', val)
            if val.within(tumor_roi):
                gotone = True
                count += 1
            elif val.intersects(tumor_roi):
                gotone = True
                count += 1
            elif tumor_roi.within(val):
                gotone = True
                count += 1
            elif tumor_roi.intersects(val):
                gotone = True
                count += 1
            if gotone:
                rtn_jfiles.append(jfile)
                # rtn_obj.update({key: val})

    print('count: ', count)
    elapsed_time = time.time() - start_time
    print('Runtime get_poly_within: ')
    print(time.strftime("%H:%M:%S", time.gmtime(elapsed_time)))

    return rtn_jfiles


def get_polygons_within_tumors(poly_map_list, tumor_list):
    """
    Reduce our list to that which our tumor areas contain.
    :param poly_map_list:
    :param tumor_list:
    :return:
    """
    start_time = time.time()
    rtn_obj = {}

    within = 0
    intersects = 0
    disjoin = 0
    for tumor_roi in tumor_list:
        for key, val in poly_map_list.items():
            # print("Key", key, 'points to', val)
            polygons = val['polygons']
            newList = []
            for poly in polygons:
                if poly.within(tumor_roi):
                    newList.append(poly)
                    within += 1
                elif poly.intersects(tumor_roi):
                    newList.append(poly)
                    intersects += 1
                # elif poly.disjoint(tumor_roi):
                #     disjoin += 1
            if newList:
                rtn_obj.update({key: newList})

    print('within', within)
    print('intersects', intersects)
    print('disjoin', disjoin)

    elapsed_time = time.time() - start_time
    print('Runtime get_polygons_within_tumors: ')
    print(time.strftime("%H:%M:%S", time.gmtime(elapsed_time)))

    return rtn_obj


# constant variables
WORK_DIR = "/data1/tdiprima/dataset"
CSV_FILE_PATH = "nfs004:/data/shared/bwang/composite_dataset"
SVS_IMAGE_PATH = "nfs001:/data/shared/tcga_analysis/seer_data/images"

# construct the argument parser and parse the arguments
ap = argparse.ArgumentParser()
ap.add_argument("-s", "--slide_name", help="svs image name")
ap.add_argument("-u", "--user_name", help="user who identified tumor regions")
ap.add_argument("-b", "--db_host", help="database host")
ap.add_argument("-t", "--tile_size", type=int, help="tile size")
args = vars(ap.parse_args())
print(args)

if not len(sys.argv) > 1:
    program_name = sys.argv[0]
    lst = ['python', program_name, '-h']
    subprocess.call(lst)  # Show help
    exit(1)

CASE_ID = args["slide_name"]
USER_NAME = args["user_name"]

SLIDE_DIR = os.path.join(WORK_DIR, CASE_ID) + os.sep
CSV_REL_PATHS = get_file_list(CASE_ID, 'config/csv_file_path.list')

# Fetch data.
# assure_path_exists(SLIDE_DIR)
# copy_src_data(SLIDE_DIR)

# Find what the pathologist circled as tumor.
tumor_mark_list = get_tumor_markup(USER_NAME)
# print('tumor_mark_list', len(tumor_mark_list))

# List of Tumor polygons
tumor_poly_list = markup_to_polygons(tumor_mark_list)
# print('tumor_poly_list', len(tumor_poly_list))

# Fetch list of data files
JSON_FILES, CSV_FILES = get_data_files()

jfile_list = get_poly_within(JSON_FILES, tumor_poly_list)
print('jfile_list len: ', len(jfile_list))

# pre_poly_map = create_map(JSON_FILES, CSV_FILES)
# print('pre_poly_map', len(pre_poly_map))
#
# poly_within = get_polygons_within_tumors(pre_poly_map, tumor_poly_list)
# print('poly_within', len(poly_within))

exit(0)
